### PR TITLE
Handled cases for initial chars

### PR DESCRIPTION
**Pull request by hiteshbedre**

### CODE REVIEW

**Comment by hiteshbedre** [comment]
Here is a playground of email cases handled: https://regex101.com/r/TjPEI6/1

**Comment by KonajuGames** [comment]
I think we have both done the same. My PR #39 also fixed those and the other remaining tests with the exception of the emoji and IDN domain name tests.

**Comment by hiteshbedre** [comment]
@KonajuGames yeah, we solved the same issue.

**Comment by hiteshbedre** [comment]
Just difference in approach is, @KonajuGames solved by handling cases via code and me via regex.

**Comment by KonajuGames** [comment]
> Just difference in approach is, @KonajuGames solved by handling cases via code and me via regex.

I extended the regex to be more generous in what it matches, to include opening and closing quotes, then filter them out in code.

**Pull request merged**
