### PR TITLE
A basic implementation of a .ODT reader

### PR DESCRIPTION
**Pull request by jfbourke**
The OpenDocumentTextReader will extract content.xml from the .ODT, parse the file and then write the text into a temporary file which is the passed into PlainTextReader for further parsing for email addresses.

### CODE REVIEW

**Comment by GStefanowich** [comment]
Since you made `PlainTextReader.DisposeAsync()` virtual, could you add to the method?

```csharp
GC.SuppressFinalize(this);
```

```csharp
public async ValueTask DisposeAsync()
{
    GC.SuppressFinalize(this);
}

**Comment by jfbourke** [comment]
Updated PlainTextReader.DisposeAsync() to clr suppress finalizer.

**Comment by GStefanowich** [comment]
@jfbourke Thanks for implementing this, I don't want to do this myself so that others still get their chance to contribute :smile: 

Is there a reason you went with writing to a temporary file, which is then read by the `PlainTextReader`?

Where you do
```csharp
private static string ExtractContent(string zipPath)
{
    using (ZipArchive archive = ZipFile.OpenRead(zipPath))
    {
        foreach (ZipArchiveEntry entry in archive.Entries)
        {
            if (entry.FullName.Equals("content.xml", StringComparison.OrdinalIgnoreCase))
            {
                using(var writer = new StreamWriter(DestinationPath, true, Encoding.UTF8, 4096))
                {
                    using(var reader = new XmlTextReader(entry.Open()))
                    {
                        while(reader.Read())
                        {
                            if (reader.NodeType == XmlNodeType.Text ||
                                reader.NodeType == XmlNodeType.CDATA)
                            {
                                writer.WriteLine(reader.ReadContentAsString());
                            }
                        }
                    }
                }

                return DestinationPath;
            }
        }
    }
    
    throw new Exception($"Unable to load content.xml from '{zipPath}'");
}
```

Would it not also be doable to just implement `ILineReader` and return `reader.ReadContentAsString()`?

```csharp
public async IAsyncEnumerable<string?> ReadLineAsync([EnumeratorCancellation] CancellationToken cancellation = default)
{
    using (ZipArchive archive = ZipFile.OpenRead(this.ZipPath))
    {
        foreach (ZipArchiveEntry entry in archive.Entries)
        {
            if (entry.FullName.Equals("content.xml", StringComparison.OrdinalIgnoreCase))
            {
                using(var reader = new XmlTextReader(entry.Open()))
                {
                    while(await reader.ReadAsync())
                    {
                        if (reader.NodeType == XmlNodeType.Text ||
                            reader.NodeType == XmlNodeType.CDATA)
                        {
                            yield return await reader.ReadContentAsStringAsync();
                        }
                    }
                }

                yield break;
            }
        }
    }
    
    throw new Exception($"Unable to load content.xml from '{this.ZipPath}'");
}
```

I don't see where the overhead of reading, writing, and reading again is worth it

**Comment by jfbourke** [comment]
@GStefanowich agree, will refactor it now.

**Pull request merged**
